const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Orbit,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Turret,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.ResetDoubleJump,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetPos
	];
};
self.C3_JsPropNameTable = [
	{DoubleJumpCount: 0},
	{CurrentJumps: 0},
	{CheckpointNumber: 0},
	{Solid: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerChar: 0},
	{block: 0},
	{"10CoinDoor": 0},
	{Coin: 0},
	{Jumpthru: 0},
	{platform: 0},
	{Arrow: 0},
	{Orbit: 0},
	{MovingBlock: 0},
	{Coins: 0},
	{Anchor: 0},
	{CoinAmount: 0},
	{Turret: 0},
	{Cannon: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{DoubleJump: 0},
	{WasdControls: 0},
	{IceBlock: 0},
	{Text: 0},
	{ClockworkBlock: 0},
	{PlainClockworkBlock: 0},
	{Sine: 0},
	{SineRotateClockworkBlock: 0},
	{Rotate: 0},
	{ClockworkRing: 0},
	{Physics: 0},
	{FallingGear: 0},
	{FallingGearSpawner: 0},
	{CheckpointClockworkTower: 0},
	{BrokenTrack: 0},
	{WalkSpeed: 0},
	{DeathZone: 0},
	{MineLockedDoor: 0},
	{FallingGear2: 0},
	{ClockworkLever: 0},
	{ADoorHasOpenedSomewhere: 0},
	{MovingClockworkBlock: 0}
];

self.InstanceType = {
	PlayerChar: class extends self.ISpriteInstance {},
	block: class extends self.ISpriteInstance {},
	_10CoinDoor: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	MovingBlock: class extends self.ISpriteInstance {},
	Coins: class extends self.ITextInstance {},
	CoinAmount: class extends self.ISpriteInstance {},
	Cannon: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	DoubleJump: class extends self.ISpriteInstance {},
	WasdControls: class extends self.IInstance {},
	IceBlock: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	ClockworkBlock: class extends self.ISpriteInstance {},
	PlainClockworkBlock: class extends self.ISpriteInstance {},
	SineRotateClockworkBlock: class extends self.ISpriteInstance {},
	ClockworkRing: class extends self.ISpriteInstance {},
	FallingGear: class extends self.ISpriteInstance {},
	FallingGearSpawner: class extends self.ISpriteInstance {},
	CheckpointClockworkTower: class extends self.ISpriteInstance {},
	BrokenTrack: class extends self.ISpriteInstance {},
	WalkSpeed: class extends self.ISpriteInstance {},
	DeathZone: class extends self.ISpriteInstance {},
	MineLockedDoor: class extends self.ISpriteInstance {},
	FallingGear2: class extends self.ISpriteInstance {},
	ClockworkLever: class extends self.ISpriteInstance {},
	ADoorHasOpenedSomewhere: class extends self.ITextInstance {},
	MovingClockworkBlock: class extends self.ISpriteInstance {}
}